-- ==============================================================================
-- PROJECT: CareConnect - Patient-Provider Electronic Health Record (EHR) System
-- DOMAIN: Healthcare & Health Informatics (HIPAA Compliant Architecture)
-- TARGET DATABASE: Oracle Database 19c / 21c / Express Edition (XE)
-- AUTHOR: CareConnect Engineering Team
-- GENERATED: September 29, 2026
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. DROP EXISTING OBJECTS (CLEAN SLATE)
-- ------------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRESCRIPTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIAGNOSTIC_ORDERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ENCOUNTERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE APPOINTMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PATIENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ------------------------------------------------------------------------------
-- 2. TABLE: USERS (Role-Based Access Control: Doctor, Patient, Admin)
-- ------------------------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 101 INCREMENT BY 1) PRIMARY KEY,
    USERNAME        VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(255) NOT NULL, -- BCrypt Salted Hash ($2a$12$...)
    ROLE            VARCHAR2(30) NOT NULL,  -- ROLE_DOCTOR, ROLE_PATIENT, ROLE_ADMIN, ROLE_NURSE
    FULL_NAME       VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    PHONE           VARCHAR2(25),
    DEPARTMENT      VARCHAR2(100),          -- e.g. Internal Medicine, Health Informatics
    IS_ACTIVE       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_USER_ROLE CHECK (ROLE IN ('ROLE_DOCTOR', 'ROLE_PATIENT', 'ROLE_ADMIN', 'ROLE_NURSE', 'ROLE_PHARMACIST'))
);

-- ------------------------------------------------------------------------------
-- 3. TABLE: PATIENTS (Master Patient Index - MPI Demographics)
-- ------------------------------------------------------------------------------
CREATE TABLE PATIENTS (
    PATIENT_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    USER_ID             NUMBER,                 -- Optional link to patient portal credentials
    MRN                 VARCHAR2(30) NOT NULL UNIQUE, -- Medical Record Number (e.g. MRN-2026-0042)
    FIRST_NAME          VARCHAR2(50) NOT NULL,
    LAST_NAME           VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH       DATE NOT NULL,
    AGE                 NUMBER(3) NOT NULL,
    GENDER              VARCHAR2(20) NOT NULL,  -- Male, Female, Other
    BLOOD_GROUP         VARCHAR2(10) NOT NULL,  -- O+, A+, B+, AB+, O-, A-, B-, AB-
    PHONE               VARCHAR2(25) NOT NULL,
    EMERGENCY_CONTACT   VARCHAR2(150),
    ALLERGIES           VARCHAR2(300) DEFAULT 'None (NKDA)' NOT NULL, -- Penicillin, Sulfa, etc.
    ASSIGNED_ROOM       VARCHAR2(50) DEFAULT 'Exam Room 3',
    STATUS              VARCHAR2(30) DEFAULT 'Admitted' NOT NULL,      -- Admitted, In Consultation, Discharged
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PATIENT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL,
    CONSTRAINT CHK_PATIENT_GENDER CHECK (GENDER IN ('Male', 'Female', 'Other'))
);

-- ------------------------------------------------------------------------------
-- 4. TABLE: APPOINTMENTS (Clinical Scheduling & Patient Consultations)
-- ------------------------------------------------------------------------------
CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 701 INCREMENT BY 1) PRIMARY KEY,
    PATIENT_ID          NUMBER NOT NULL,
    DOCTOR_ID           NUMBER NOT NULL,
    APPOINTMENT_DATE    DATE NOT NULL,
    TIME_SLOT           VARCHAR2(30) NOT NULL,   -- e.g. '10:30 AM - 11:00 AM'
    REASON_FOR_VISIT    VARCHAR2(255) NOT NULL,  -- Symptoms / Chief Complaint
    STATUS              VARCHAR2(30) DEFAULT 'Confirmed' NOT NULL, -- Confirmed, Completed, Cancelled
    ROOM_NUMBER         VARCHAR2(50) DEFAULT 'Exam Room 3',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_APPT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_APPT_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_APPT_STATUS CHECK (STATUS IN ('Confirmed', 'Completed', 'Cancelled', 'No-Show'))
);

-- ------------------------------------------------------------------------------
-- 5. TABLE: ENCOUNTERS (Clinical Documentation & SOAP Notes)
-- ------------------------------------------------------------------------------
CREATE TABLE ENCOUNTERS (
    ENCOUNTER_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001 INCREMENT BY 1) PRIMARY KEY,
    PATIENT_ID          NUMBER NOT NULL,
    DOCTOR_ID           NUMBER NOT NULL,
    ENCOUNTER_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHIEF_COMPLAINT     VARCHAR2(500) NOT NULL,
    
    -- Triage Physiological Vitals
    BP_SYSTOLIC         NUMBER(4) NOT NULL,     -- mmHg
    BP_DIASTOLIC        NUMBER(4) NOT NULL,     -- mmHg
    HEART_RATE          NUMBER(4) NOT NULL,     -- bpm
    TEMP_FAHRENHEIT     NUMBER(4,1) NOT NULL,   -- °F
    SPO2_PERCENT        NUMBER(3) NOT NULL,     -- %
    RESP_RATE           NUMBER(3) DEFAULT 18,   -- breaths/min
    
    -- Structured Clinical SOAP Note Quadrants
    SOAP_SUBJECTIVE     CLOB NOT NULL,          -- Patient history and reported symptoms
    SOAP_OBJECTIVE      CLOB NOT NULL,          -- Physical examination & lab findings
    SOAP_ASSESSMENT     CLOB NOT NULL,          -- Differential diagnoses (ICD-10 coded)
    SOAP_PLAN           CLOB NOT NULL,          -- Treatment regimens, prescriptions, orders
    
    -- Electronic Signing & HIPAA Locking
    IS_SIGNED           NUMBER(1) DEFAULT 0 NOT NULL,
    SIGNED_AT           VARCHAR2(50),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ENCOUNTER_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ENCOUNTER_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------------------------
-- 6. TABLE: DIAGNOSTIC_ORDERS (CPOE - Computerized Provider Order Entry)
-- ------------------------------------------------------------------------------
CREATE TABLE DIAGNOSTIC_ORDERS (
    ORDER_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 301 INCREMENT BY 1) PRIMARY KEY,
    ENCOUNTER_ID        NUMBER,
    PATIENT_ID          NUMBER NOT NULL,
    DOCTOR_ID           NUMBER NOT NULL,
    ORDER_TYPE          VARCHAR2(50) NOT NULL,   -- Laboratory, Radiology, Procedure
    TEST_NAME           VARCHAR2(150) NOT NULL,  -- Complete Blood Count (CBC), Chest X-Ray
    PRIORITY            VARCHAR2(20) DEFAULT 'Routine' NOT NULL, -- Routine, Urgent, STAT
    STATUS              VARCHAR2(30) DEFAULT 'Pending' NOT NULL, -- Pending, Processing, Completed, Cancelled
    RESULT_FINDINGS     CLOB,                   -- Lab specialist or radiologist report
    ORDERED_AT          VARCHAR2(30) NOT NULL,
    FULFILLED_AT        VARCHAR2(30),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDER_ENCOUNTER FOREIGN KEY (ENCOUNTER_ID) REFERENCES ENCOUNTERS(ENCOUNTER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_ORDER_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_ORDER_PRIORITY CHECK (PRIORITY IN ('Routine', 'Urgent', 'STAT')),
    CONSTRAINT CHK_ORDER_STATUS CHECK (STATUS IN ('Pending', 'Processing', 'Completed', 'Cancelled'))
);

-- ------------------------------------------------------------------------------
-- 7. TABLE: PRESCRIPTIONS (e-Prescribing & Medication Management)
-- ------------------------------------------------------------------------------
CREATE TABLE PRESCRIPTIONS (
    PRESCRIPTION_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 501 INCREMENT BY 1) PRIMARY KEY,
    ENCOUNTER_ID        NUMBER,
    PATIENT_ID          NUMBER NOT NULL,
    DOCTOR_ID           NUMBER NOT NULL,
    MEDICATION_NAME     VARCHAR2(150) NOT NULL, -- e.g. Albuterol Sulfate, Lisinopril
    DOSAGE              VARCHAR2(50) NOT NULL,  -- e.g. 10 mg, 90 mcg
    FREQUENCY           VARCHAR2(100) NOT NULL, -- e.g. Once daily in the morning
    DURATION            VARCHAR2(50) NOT NULL,  -- e.g. 30 days
    STATUS              VARCHAR2(30) DEFAULT 'Active' NOT NULL, -- Active, Discontinued, Completed
    OVERRIDE_REASON     VARCHAR2(300),          -- Clinical decision support allergy override
    PRESCRIBED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_RX_ENCOUNTER FOREIGN KEY (ENCOUNTER_ID) REFERENCES ENCOUNTERS(ENCOUNTER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_RX_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RX_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_RX_STATUS CHECK (STATUS IN ('Active', 'Discontinued', 'Completed'))
);

-- ------------------------------------------------------------------------------
-- 8. TABLE: MEDICAL_REPORTS (Diagnostic Documents & Scans Vault)
-- ------------------------------------------------------------------------------
CREATE TABLE MEDICAL_REPORTS (
    REPORT_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    PATIENT_ID          NUMBER NOT NULL,
    PATIENT_NAME        VARCHAR2(100),
    TITLE               VARCHAR2(150) NOT NULL,
    REPORT_TYPE         VARCHAR2(50) NOT NULL,   -- LABORATORY, RADIOLOGY, PATHOLOGY, PRESCRIPTION, DISCHARGE_SUMMARY, OTHER
    FILE_NAME           VARCHAR2(200) NOT NULL,
    FILE_TYPE           VARCHAR2(80),
    FILE_SIZE           VARCHAR2(30),
    FILE_DATA           CLOB,                   -- Base64 Document URI
    NOTES               VARCHAR2(500),
    UPLOADED_BY         VARCHAR2(100) NOT NULL,
    UPLOADER_ROLE       VARCHAR2(30) NOT NULL,  -- ROLE_DOCTOR, ROLE_PATIENT, ROLE_ADMIN
    REPORT_DATE         VARCHAR2(30),
    UPLOADED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_REPORT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE
);

-- ------------------------------------------------------------------------------
-- 9. TABLE: AUDIT_LOGS (HIPAA Security & Access Audit Trail)
-- ------------------------------------------------------------------------------
CREATE TABLE AUDIT_LOGS (
    LOG_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 901 INCREMENT BY 1) PRIMARY KEY,
    USER_NAME           VARCHAR2(100) NOT NULL,
    ACTION_TYPE         VARCHAR2(50) NOT NULL,  -- CREATE_ORDER, RECORD_VITALS, VIEW_RECORD, USER_PROVISIONED, ADMIN_LOGIN
    EVENT_DETAILS       VARCHAR2(500) NOT NULL,
    IP_ADDRESS          VARCHAR2(50) DEFAULT '192.168.1.100',
    EVENT_TIMESTAMP     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ------------------------------------------------------------------------------
-- 10. PERFORMANCE INDEXES
-- ------------------------------------------------------------------------------
CREATE INDEX IDX_PATIENTS_MRN ON PATIENTS(MRN);
CREATE INDEX IDX_PATIENTS_NAME ON PATIENTS(LAST_NAME, FIRST_NAME);
CREATE INDEX IDX_ENCOUNTERS_PATIENT ON ENCOUNTERS(PATIENT_ID);
CREATE INDEX IDX_ORDERS_PATIENT ON DIAGNOSTIC_ORDERS(PATIENT_ID, STATUS);
CREATE INDEX IDX_PRESCRIPTIONS_PATIENT ON PRESCRIPTIONS(PATIENT_ID, STATUS);
CREATE INDEX IDX_REPORTS_PATIENT ON MEDICAL_REPORTS(PATIENT_ID, REPORT_TYPE);
CREATE INDEX IDX_APPOINTMENTS_DATE ON APPOINTMENTS(DOCTOR_ID, APPOINTMENT_DATE);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOGS(EVENT_TIMESTAMP);

-- ==============================================================================
-- 10. REALISTIC CLINICAL SEED DATA (POPULATION)
-- ==============================================================================

-- A. USERS (Password for all accounts is 'password123' hashed with BCrypt)
-- Hash: $2a$10$wK1.c3j9d6P.Y4xV9Zt9eecY2m.hW8bN7R5j0Zg1p5vO4q2s1t0uO
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, ROLE, FULL_NAME, EMAIL, PHONE, DEPARTMENT) VALUES
(101, 'dr_smith', '$2a$10$wK1.c3j9d6P.Y4xV9Zt9eecY2m.hW8bN7R5j0Zg1p5vO4q2s1t0uO', 'ROLE_DOCTOR', 'Dr. Sarah Smith, MD', 'dr.smith@careconnect.org', '+1 (555) 100-0101', 'Internal Medicine & Pulmonology');

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, ROLE, FULL_NAME, EMAIL, PHONE, DEPARTMENT) VALUES
(102, 'john_doe', '$2a$10$wK1.c3j9d6P.Y4xV9Zt9eecY2m.hW8bN7R5j0Zg1p5vO4q2s1t0uO', 'ROLE_PATIENT', 'John Doe', 'john.doe@gmail.com', '+1 (555) 234-5678', 'Outpatient Patient');

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, ROLE, FULL_NAME, EMAIL, PHONE, DEPARTMENT) VALUES
(103, 'admin_alex', '$2a$10$wK1.c3j9d6P.Y4xV9Zt9eecY2m.hW8bN7R5j0Zg1p5vO4q2s1t0uO', 'ROLE_ADMIN', 'Alex Morgan', 'alex.admin@careconnect.org', '+1 (555) 300-0303', 'Health Informatics & Security');

INSERT INTO USERS (USER_ID, USERNAME, PASSWORD_HASH, ROLE, FULL_NAME, EMAIL, PHONE, DEPARTMENT) VALUES
(104, 'dr_chang', '$2a$10$wK1.c3j9d6P.Y4xV9Zt9eecY2m.hW8bN7R5j0Zg1p5vO4q2s1t0uO', 'ROLE_DOCTOR', 'Dr. Michael Chang, MD', 'dr.chang@careconnect.org', '+1 (555) 100-0102', 'Cardiology & Preventive Medicine');

-- B. PATIENTS (MPI)
INSERT INTO PATIENTS (PATIENT_ID, USER_ID, MRN, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, AGE, GENDER, BLOOD_GROUP, PHONE, EMERGENCY_CONTACT, ALLERGIES, ASSIGNED_ROOM, STATUS) VALUES
(1, 102, 'MRN-2026-0042', 'John', 'Doe', TO_DATE('1985-04-12', 'YYYY-MM-DD'), 41, 'Male', 'O+', '+1 (555) 234-5678', 'Jane Doe (Wife) - +1 (555) 234-5679', 'Penicillin, NSAIDs (Aspirin/Ibuprofen)', 'Exam Room 3', 'In Consultation');

INSERT INTO PATIENTS (PATIENT_ID, USER_ID, MRN, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, AGE, GENDER, BLOOD_GROUP, PHONE, EMERGENCY_CONTACT, ALLERGIES, ASSIGNED_ROOM, STATUS) VALUES
(2, NULL, 'MRN-2026-0089', 'Maria', 'Gonzalez', TO_DATE('1968-11-23', 'YYYY-MM-DD'), 57, 'Female', 'A+', '+1 (555) 876-5432', 'Carlos (Son) - +1 (555) 876-5430', 'Sulfa Antibiotics', 'Waiting Room', 'Scheduled');

INSERT INTO PATIENTS (PATIENT_ID, USER_ID, MRN, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, AGE, GENDER, BLOOD_GROUP, PHONE, EMERGENCY_CONTACT, ALLERGIES, ASSIGNED_ROOM, STATUS) VALUES
(3, NULL, 'MRN-2026-0104', 'Robert', 'Chen', TO_DATE('1995-07-08', 'YYYY-MM-DD'), 31, 'Male', 'B+', '+1 (555) 456-7890', 'Lin Chen - +1 (555) 456-7891', 'None (NKDA)', 'Completed', 'Discharged');

-- C. APPOINTMENTS
INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, TIME_SLOT, REASON_FOR_VISIT, STATUS, ROOM_NUMBER) VALUES
(701, 1, 101, TO_DATE('2026-10-14', 'YYYY-MM-DD'), '10:30 AM', 'Follow-up Consultation: Blood Pressure & Bronchitis', 'Confirmed', 'Exam Room 3');

INSERT INTO APPOINTMENTS (APPOINTMENT_ID, PATIENT_ID, DOCTOR_ID, APPOINTMENT_DATE, TIME_SLOT, REASON_FOR_VISIT, STATUS, ROOM_NUMBER) VALUES
(702, 2, 101, TO_DATE('2026-09-29', 'YYYY-MM-DD'), '02:00 PM', 'Asthma inhaler refill evaluation and spirometry review', 'Confirmed', 'Exam Room 3');

-- D. ENCOUNTERS & SOAP NOTES
INSERT INTO ENCOUNTERS (ENCOUNTER_ID, PATIENT_ID, DOCTOR_ID, CHIEF_COMPLAINT, BP_SYSTOLIC, BP_DIASTOLIC, HEART_RATE, TEMP_FAHRENHEIT, SPO2_PERCENT, RESP_RATE, SOAP_SUBJECTIVE, SOAP_OBJECTIVE, SOAP_ASSESSMENT, SOAP_PLAN, IS_SIGNED, SIGNED_AT) VALUES
(1001, 1, 101, 'Chest tightness and productive morning cough for 4 days.', 142, 92, 86, 99.1, 95, 18,
'Patient reports persistent cough with yellowish sputum and mild chest tightness when walking briskly. Denies fever or chills.',
'Lungs: Scattered mild expiratory wheezes at right base. Heart: Regular rhythm, S1/S2 present. BP elevated at 142/92.',
'1. Acute Bronchitis (J20.9)' || CHR(10) || '2. Stage 2 Essential Hypertension (I10)',
'1. Order STAT Chest X-Ray and CBC.' || CHR(10) || '2. Prescribe Albuterol Inhaler (2 puffs q4-6h PRN).' || CHR(10) || '3. Prescribe Lisinopril 10mg daily for BP.' || CHR(10) || '4. Contraindication: Avoid Penicillin/Amoxicillin due to documented allergy.',
0, NULL);

-- E. DIAGNOSTIC ORDERS (CPOE)
INSERT INTO DIAGNOSTIC_ORDERS (ORDER_ID, ENCOUNTER_ID, PATIENT_ID, DOCTOR_ID, ORDER_TYPE, TEST_NAME, PRIORITY, STATUS, RESULT_FINDINGS, ORDERED_AT, FULFILLED_AT) VALUES
(301, 1001, 1, 101, 'Laboratory', 'Complete Blood Count (CBC)', 'STAT', 'Pending', NULL, '09:45 AM', NULL);

INSERT INTO DIAGNOSTIC_ORDERS (ORDER_ID, ENCOUNTER_ID, PATIENT_ID, DOCTOR_ID, ORDER_TYPE, TEST_NAME, PRIORITY, STATUS, RESULT_FINDINGS, ORDERED_AT, FULFILLED_AT) VALUES
(302, 1001, 1, 101, 'Radiology', 'Chest X-Ray (PA & Lateral)', 'Urgent', 'Completed', 'Normal heart size. Mild peribronchial thickening consistent with bronchitis. No pneumonia or pneumothorax.', '09:50 AM', '10:15 AM');

-- F. PRESCRIPTIONS
INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, ENCOUNTER_ID, PATIENT_ID, DOCTOR_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, DURATION, STATUS, OVERRIDE_REASON) VALUES
(501, 1001, 1, 101, 'Albuterol Sulfate Inhaler', '90 mcg', '2 puffs every 4-6 hours as needed', '14 days', 'Active', NULL);

INSERT INTO PRESCRIPTIONS (PRESCRIPTION_ID, ENCOUNTER_ID, PATIENT_ID, DOCTOR_ID, MEDICATION_NAME, DOSAGE, FREQUENCY, DURATION, STATUS, OVERRIDE_REASON) VALUES
(502, 1001, 1, 101, 'Lisinopril Oral Tablet', '10 mg', 'Once daily in the morning', '30 days', 'Active', NULL);

-- G. HIPAA AUDIT LOGS
INSERT INTO AUDIT_LOGS (LOG_ID, USER_NAME, ACTION_TYPE, EVENT_DETAILS, IP_ADDRESS) VALUES
(901, 'Dr. Sarah Smith', 'APPOINTMENT_SCHEDULED', 'Booked appointment with Dr. Sarah Smith on 2026-10-14 at 10:30 AM for John Doe', '192.168.1.102');

INSERT INTO AUDIT_LOGS (LOG_ID, USER_NAME, ACTION_TYPE, EVENT_DETAILS, IP_ADDRESS) VALUES
(902, 'Dr. Sarah Smith', 'CREATE_ORDER', 'Ordered STAT Chest X-Ray for John Doe (MRN-2026-0042)', '192.168.1.102');

INSERT INTO AUDIT_LOGS (LOG_ID, USER_NAME, ACTION_TYPE, EVENT_DETAILS, IP_ADDRESS) VALUES
(903, 'Dr. Sarah Smith', 'CREATE_ORDER', 'Ordered STAT CBC for John Doe (MRN-2026-0042)', '192.168.1.102');

INSERT INTO AUDIT_LOGS (LOG_ID, USER_NAME, ACTION_TYPE, EVENT_DETAILS, IP_ADDRESS) VALUES
(904, 'Dr. Sarah Smith', 'VIEW_RECORD', 'Opened patient chart for John Doe', '192.168.1.102');

INSERT INTO AUDIT_LOGS (LOG_ID, USER_NAME, ACTION_TYPE, EVENT_DETAILS, IP_ADDRESS) VALUES
(905, 'Alex Morgan', 'ADMIN_LOGIN', 'Security login from IP 192.168.1.45', '192.168.1.45');

COMMIT;
-- ==============================================================================
-- END OF SCRIPT. TABLES, CONSTRAINTS, INDEXES, AND SEED RECORDS ARE READY.
-- ==============================================================================
